name: Trigger on push to main branch 

on: 
  push: 
    branches:
      - main
    paths :
      - ".github/workflows/push.yml"
      - "basicCICD/**"  

jobs: 
  demo: 
    runs-on: "ubuntu-latest"

    steps: 
      - run: echo "running on push to main"